version: "3"
services:
  discord-scraper:
    build: .
    env_file:
      - .env
    environment:
      MONGODB_HOST: mongodb
    networks:
      - discord-network
    restart: always
  mongodb:
    image: mongo
    logging:
      driver: "none"
    networks:
      - discord-network
    volumes:
      - "discord-scraper:/data/db"
    restart: always
networks:
  discord-network:
volumes:
  discord-scraper:
